apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-{{ .Release.Name }}
  name: my-service-{{ .Release.Name }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: deploy-{{ .Release.Name }}
  type: LoadBalancer
status:
  loadBalancer: {}
